language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8
addons:
  sonarcloud:
    organization: "rchukh-github"
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar